version: '3'
services:
  db: # the service hosting your MySQL instance
    image: mysql:5.7 # the image and tag docker will pull from docker hub
    container_name: dev_db
    volumes: # this section allows you to configure persistence within multiple restarts
      - db_data:/var/lib/mysql
    restart: always # if the db crash somehow, restart it
    environment: # env variables, you usually set this to override existing ones
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

volumes:
  db_data:
