version: "3.7"
services:
  front:
    container_name: algoflex_front
    env_file:
      - front.env
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    expose:
      - 3000
    restart: always