name: deploy_workflow

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get specific changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v17.3
      with:
        files: algoflex_backend
    - name: Deploying on Heroku
      # if: steps.changed-files-specific.outputs.any_changed == 'true'
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "staging-algoflex"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        usedocker: true
        appdir: "algoflex_backend"
      env:
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
